version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing package.json dependencies...
      - npm ci
  pre_build: 
    commands:
      - echo Running pre-build commands...
      - npm run test:ci
  build:
    commands:
      - echo Running build commands...
      - npm run build:all
  post_build:
    commands:
      - npx semantic-release
artifacts:
  files:
    - build/**/*
